version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      eslint:
        patterns:
          - "@egy186/eslint-config"
          - "eslint"
    versioning-strategy: increase
